config/routes.rb
Rails.application.routes.draw do

  resources :experts do
    member do
      post 'add_friend'
      get 'find_friend'
    end
  end

  root 'experts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/expert.rb
class Expert < ActiveRecord::Base
  has_many :headers
  has_and_belongs_to_many :friends,
              class_name: "Expert",
              join_table: :friendships,
              foreign_key: :user_id,
              association_foreign_key: :friend_user_id
  after_create :grab_headers_from_website, :shorten_url


  def grab_headers_from_website
    response = HTTParty.get(self.website)
    doc = Nokogiri::HTML(response.body)
    get_headers(doc, "h1")
    get_headers(doc, "h2")
    get_headers(doc, "h3")
  end

  def get_headers(doc, header_tag)
    headers_by_tag = doc.css(header_tag)
    headers_by_tag.each do |header|
      self.headers.create(text: header.text)
    end
  end

  def shorten_url
    self.short_url = Bitly.client.shorten(website).short_url
    save
  end

  def add_friend(expert)
    self.friends << expert
    expert.friends << self
  end

  def find_friend(subject)
    target_expert_id = Header.find_by_text(subject).expert.id
    @already_visited = []
    path = []
    path = find_shortest_path(self, target_expert_id, path, subject)
    path << self.name
    path.reverse
  end

  def find_shortest_path(current_expert, target_expert_id, path, subject)
    begin
      target = current_expert.friends.find(target_expert_id)
    rescue
    end
    unless target.nil?
      path << Expert.find(target_expert_id).name + "(\"#{subject}\")"
      return path
    end

    current_expert.friends.each do |friend|
      unless @already_visited.include? friend.id
        @already_visited << friend.id
        path = find_shortest_path(friend, target_expert_id, path, subject)
        path << friend.name if !path.empty?
      end
    end
    path
  end

end

app/models/header.rb
class Header < ActiveRecord::Base
  belongs_to :expert
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/experts_controller.rb
class ExpertsController < ApplicationController
  before_action :set_expert, only: [:show, :destroy, :add_friend, :find_friend]
  respond_to? :html, :json
  protect_from_forgery with: :null_session, only: [:add_friend, :find_friend]

  def index
    @experts = Expert.all
  end

  def show
  end

  def new
    @expert = Expert.new
  end

  def create
    @expert = Expert.new(expert_params)

    respond_to do |format|
      if @expert.save
        format.html { redirect_to @expert, notice: 'Expert was successfully created.' }
        format.json { render :show, status: :created, location: @expert }
      else
        format.html { render :new }
        format.json { render json: @expert.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @expert.destroy
  end

  def add_friend
    friend_name = params['friend']
    friend = Expert.find_by_name(friend_name)
    @expert.add_friend(friend)
    head :ok
  end

  def find_friend
    subject = params['subject']
    if subject.blank?
      respond_to do |format|
        head :unprocessable_entity
      end
      return
    end
    friend_path = @expert.find_friend(subject)
    respond_to do |format|
      format.json { render json: friend_path, status: :ok}
    end
  end

 private
  def set_expert
    @expert = Expert.find(params[:id])
  end

  def expert_params
    params.require(:expert).permit(:name, :website)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/experts/index.html.erb
<h1>Experts</h1>
<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Short URL</th>
      <th>Number of Friends</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>

    <% @experts.each do |expert| %>
      <tr>
        <td><%= expert.name %></td>
        <td><%= expert.short_url %></td>
        <td><%= expert.friends.count %></td>
        <td><%= link_to 'Show', expert %></td>
        <td><%= link_to 'Destroy', expert, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  <tbody>
  </table>

  Create <%= link_to 'New Expert', new_expert_path %>

app/views/experts/new.html.erb
<h1> Create an Expert </h1>
<%= form_for @expert, url: {action: "create"} do |form| %>
  <div class="form-group">
    <label for="expert_name">Name</label>
    <%= form.text_field :name %>
  </div>
  <div class="form-group">
    <label for="expert_website">Website</label>
    <%= form.text_field :website %>
  </div>
  <%= form.submit %>
<% end %>
<%= link_to 'Back', experts_path %>

app/views/experts/show.html.erb
<%= javascript_include_tag "friend" %>

<h1><%= @expert.name %></h1>
<label>Website </label><%= @expert.website %>
<br>
<label>Shortened Website </label><%= @expert.short_url %>
<br>
<label>Headers</label>
<ul>
<% @expert.headers.each do |header| %>
  <li><%= header.text %></li>
<% end %>
</ul>
<br>


<label>Friends Pages:</label>
<ul>
<% @expert.friends.each do |friend| %>
  <li><a href="<%= friend.website %>"><%= friend.website %></a></li>
<% end %>
</ul>
<br>

<input id="expert_id" type="hidden" value="<%= @expert.id %>">

<form class="show form">
  <label> Add Friend </label>
  <input id="friend_to_add" type="text"></input>
  <button type="button" class="btn btn-primary"id="add_friend_button"> Add</button>
</form>
<br>

<form>
  <label> Find Friend by Subject</label>
  <input id="friend_subject_to_add" type="text"></input>
  <button type="button" class="btn btn-primary" id="find_friend_button"> Find</button>
</form>



<div class="modal" tabindex="-1" role="dialog" id='path_modal'>
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Friends to get to expert</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body" id="path-body">

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>





<%= link_to 'Back', experts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EverlyWell</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>